name: blog_env3
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyterlab=4
  - numpy
  - matplotlib
  - seaborn
  - networkx=2
  - sphinx
  - tqdm
  - future
  - pip
  - nbstripout
  - nbdime
  - python-lsp-server
  - jupyterlab-lsp
  - pip:
    - empiricaldist
    - dspy-ai==2.4.3
    - ipython==8.18.1
    - google-generativeai==0.5.0
    - ipykernel
    - git+https://github.com/hodgepodge73/dspy.git
